### ISSUE TITLE
Contribute.md link

### ISSUE THREAD

**Issue by vsoch** [FelixHenninger/open-science-knowledge-base#6]
hey @FelixHenninger ! I had thought that you forgot to add the contribute.md document to the repo,  but I just found it under ` content/change/community/contribute.md`. You can assign me to fix this link - I'm doing a PR now! Just a quick question - are there instructions for developing locally? What kind of server (jekyll, other?) are you using when you develop?

**Comment by vsoch** [comment]
Ahh you must be using --> https://www.mkdocs.org/ ?

**Comment by vsoch** [comment]
I'm going to add docs for local development too - I just figured out mkdocs. It's cool!

**Comment by FelixHenninger** [comment]
Hi Vanessa, it's great to have you around -- I'm sorry that the build documentation is kinda haphazard right now, I didn't expect this to go public so quickly!

I've already promised @tomhardwicke this morning that I'd add a proper `readme` and an issue template, but this day has been wild, and I've yet to get around to it. D'you wanna cover the build step, and I'll do a general introduction? I've assigned you this issue, but please let me know if there's anything I can add or help you get started with, I'd be glad to!

Best, -Felix

**Comment by vsoch** [comment]
Done! See #7  :)

**Comment by FelixHenninger** [comment]
Wow, you're amazing (not that that's news to anyone, but it bears repeating), you fixed the issue faster than I could remember to assign it to you 😄 . Thanks so much! I'm not sure where to go from here -- you wanna discuss the container section first, or would you like me to try and cherry-pick the contribution section from your PR?

**Comment by FelixHenninger** [comment]
(sorry, closing this was probably not the best idea -- this has been a long, long day!)

**Comment by vsoch** [comment]
haha no worries, I'm sending along good vibes and energy to get you through the rest of it! It's only mid-day over here so I'm not pooped out yet :P

**Comment by FelixHenninger** [comment]
Wow, thanks! I turn into a total pile of uselessness after teaching. A big shipment of electronic components and tools arrived at the office today, and I'm sitting here giddy like a child in a big pile of antistatic bags, staring at little chips, wondering what they do, and looking forward to tinkering 🙂.

**Comment by vsoch** [comment]
oh cool! Might I ask what you got? I played with a netduino a long time ago, but I'm far behind when it comes down to modern IoT stuffs. Are you building something?

**Comment by vsoch** [comment]
omg, you're amazing!! I can't wait to read the results of this!

**Comment by FelixHenninger** [comment]
Ooh, not even close, but thanks! 🙂 We'll have to see what tomorrow brings.
